### ISSUE TITLE
Need the latest fix of libbuildpack-dynatrace module in the go buildpack

### ISSUE THREAD

**Issue by manitheja1** [cloudfoundry/go-buildpack#122]
Hi Team,
I could see the libbuildpack dynatrace module in the go  buildpack is using 1.2.2 version. There has been a latest release(1.3.0) for the module which has a fix to customize oneagenturl(https://github.com/Dynatrace/libbuildpack-dynatrace/releases ).

We need that fix in the go buildpack. I know. could you please help us in getting the new release which will have the latest release of libbuildpack-dynatrace?

Thanks,
Manitheja

**Comment by ForestEckhardt** [comment]
@manitheja1 The module has been bumped in this commit 24f6cca. It will be present in the next release of the buildpack.
