### ISSUE TITLE
New go version

### ISSUE THREAD

**Issue by tyyko** [cloudfoundry/go-buildpack#17]
https://golang.org/dl/

The actual go version is 1.4.2 and the buildpack only have go versions until 1.4.1

**Comment by flavorjones** [comment]
Thanks for pointing this out!

This is actually already fixed on a branch that will shortly be merged to master. The next release will contain (and default to) 1.4.2. See commit 2373b010033eefd1dcf6b2e5b6db302215a2a599.

Thanks for using Cloud Foundry!
