### ISSUE TITLE
Custom build command

### ISSUE THREAD

**Issue by markgunnels** [cloudfoundry/go-buildpack#18]
Apologies if I missed something obvious but is there a way to execute a custom "go build" command. I want to be able to build on CloudFoundry with:

go build --ldflags '-extldflags'

**Comment by Dannyzen** [comment]
Hey @markgunnels we don't currently support this functionality. Would you mind sharing your use case?

**Comment by flavorjones** [comment]
@markgunnels Another option is to build your go binary yourself using whatever arguments you like, and use the `binary-buildpack` to run it.

**Comment by Dannyzen** [comment]
Hey @markgunnels, before closing this issue we wanted to confirm if any additional assistance was required.

**Comment by RochesterinNYC** [comment]
Closing due to lack of response.
