### ISSUE TITLE
Something that just works for some v1.4

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/go-buildpack#23]
I'm trying to deploy the same go app to various versions of CF, and with that comes to constant deprecation of golang versions.

In PivotalCF, it bundles v208, which includes golang v1.4; but not v1.4.2.

```
-----> Resource https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz is not provided by this buildpack. Please upgrade your buildpack to receive the latest resources.
-----> Installing go1.4.2... done
-----> Running: godep go install -tags cloudfoundry ./...
godep: go exec: "go": executable file not found in $PATH
```

But if I code my `Godeps/Godeps.json` for v1.4 then it stops working in newer v220+ (Pivotal WS):

```
-----> Resource https://storage.googleapis.com/golang/go1.4.linux-amd64.tar.gz is not provided by this buildpack. Please upgrade your buildpack to receive the latest resources.
-----> Installing go1.4... Staging failed: Buildpack compilation step failed
```

How do I get one Golang app to run on different go-buildpack versions/different "latest release" Pivotal products?

**Comment by drnic** [comment]
Could we support "v1.4" to "just work" and match to the oldest 1.4.X that's available? Backwards/forwards portability of an app is a challenge at the moment.

**Comment by rosenhouse** [comment]
This is an issue that Pivotal's LA CloudFoundry team has encountered in various forms for our open-source and PCF products.

What if a developer could express somehow that they've tested the app against several different versions, and that any of those versions is is ok.

I think it is ok to put the burden of being explicit on the developer.  The alternative is that my app may boot on a version of Go that I haven't tested it against.

**Comment by jtarchie** [comment]
@drnic the buildpacks try to provide a consistent experience when it comes to versioning. It is related to potentially having an untested compiler/runtime against your code in production.

The golang buildpack supports the contract that `godeps` institutes with versioning of a specific go compiler. If `godeps` happened to support the `~>1.4` syntax (or equivalent) for compiler versioning, then we'd have to support it, too.

**Comment by drnic** [comment]
Could we also package 1.4.X as 1.4 and keep it in the buildpack until we stop supporting 1.4.X family?

**Comment by flavorjones** [comment]
I totally understand the problem. Not sure there's an easy fix, but we'll see what we can come up with.

**Comment by flavorjones** [comment]
@drnic - If we were able to get golang v1.4.1 into the next cf-release, I believe that would address this issue. Confirm/deny?

**Comment by flavorjones** [comment]
@drnic - your other option is to use the binary buildpack to ship a precompiled Go executable.

But we're going to try to get golang 1.4.1 into a go-buildpack release, and get that into v222.

**Comment by drnic** [comment]
I just tore down my PCF deployment this afternoon :/ if v1.4.1 is in cf 208 (latest PCF release) then yeah that should work

**Comment by flavorjones** [comment]
See related: https://github.com/tools/godep/issues/297 and https://github.com/heroku/heroku-buildpack-go/issues/100

**Comment by Dannyzen** [comment]
Update: https://www.pivotaltracker.com/story/show/106117500 is open for this ticket and should be completed early 2016.

**Comment by Dannyzen** [comment]
Thanks for submitting this request. It has been completed and in [Release v1.7.2](https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.7.2)
