### ISSUE TITLE
Getting deprecation warning

### ISSUE THREAD

**Issue by kashyap-splunk** [cloudfoundry/go-buildpack#233]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
CF CLI v7.3.0 (using Pivotal distribution of Cloud-foundry v2.12.3)

What version of the buildpack you are using?
1.9.37

If you were attempting to accomplish a task, what was it you were attempting to do?
I was trying to build and push a firehose nozzle (splunk-firehose-nozzle) to cf using go-builpack.

What did you expect to happen?
Successful build without any error or warning.

What was the actual behavior?
A warning was displayed to use 'appdynamics' buildpack for instrumentation.

Please confirm where necessary:
* [x] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

The Warning:
WARNING * * [DEPRECATION WARNING]:
WARNING * * Please use AppDynamics extension buildpack for Golang Application instrumentation
WARNING * * for more details: https://docs.pivotal.io/partners/appdynamics/multibuildpack.html

I am not able to figure out a way to avoid this warning if I don't want to use AppDynamics instrumentation. Do I need to use any other buildpack for this nozzle app?

**Comment by menehune23** [comment]
Hi @kashyap-splunk, can you please provide a minimal app that reproduces this (archive or git repo)?

**Comment by kashyap-splunk** [comment]
Here is the minimal app to reproduce this: https://github.com/kashyap-splunk/test-go-buildpack/
I just ran below command to push this to cf:
`cf push test-go-buildpack`

For reference, the nozzle I am trying to build: https://github.com/cloudfoundry-community/splunk-firehose-nozzle

**Comment by kashyap-splunk** [comment]
@menehune23 Let me know if more information needed.

**Comment by menehune23** [comment]
Thanks @kashyap-splunk. We'll take a look when we get a chance. We've been out for the holidays and we're also a small team. Thanks for your patience.

**Comment by kashyap-splunk** [comment]
Hey @menehune23, just wanted to know if you guys got chance to look at this and if there is any update. Thanks.

**Comment by menehune23** [comment]
Hi @kashyap-splunk, I'm not on the team that manages these buildpacks anymore, but I'll rope in @cloudfoundry/cf-buildpacks

**Comment by brayanhenao** [comment]
Hi @kashyap-splunk 

Sorry for the late response. After reviewing this issue we realized that this warning should only be displayed when someone tries to bind an AppDynamics service with the Buildpack. For cases where this is not required/used, it will not be shown.

These changes will be available in the next Go Builpdack release (`v1.9.41`)

**Comment by brayanhenao** [comment]
@kashyap-splunk `Go Buildpack v1.9.41` [released](https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.9.41) with the corresponding fix.
