### ISSUE TITLE
Vendoring support in 1.5+

### ISSUE THREAD

**Issue by mandolyte** [cloudfoundry/go-buildpack#25]
Go as of 1.5 has built in support vendoring and no longer requires godep. It requires env variable to use in 1.5 since it is experimental (GO15VENDOREXPERIMENT=1). But for 1.6 it will be the default.

This script requires godep, which I think is no longer needed.

**Comment by Dannyzen** [comment]
Hi @mandolyte thanks for the feedback. We'll discuss including these changes when 1.6 becomes the default and is supported by the buildpack.

**Comment by jtarchie** [comment]
@mandolyte there is [undocumented support](https://github.com/cloudfoundry/go-buildpack/blob/master/bin/compile#L202-L223) for it, right now. If you `cf set-env GO15VENDOREXPERIMENT 1` with an app that doesn't have `Godeps` you should be set. Please give it a try and give us feedback. :-)

**Comment by Dannyzen** [comment]
@mandolyte  Do you still need assistance or can we close this issue out?

**Comment by mandolyte** [comment]
None needed. I would expect that after 1.6 is released and you begin using
then all *required* dependencies on Godep could be removed.

Please close,
Regards.

Cecil
https://google.me/+CecilNew

**Comment by Dannyzen** [comment]
Closing as requested. Notably, https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.7.3 contains support for 1.6

**Comment by chendrix** [comment]
Is there eventually going to be support even without setting `cf set-env GO15VENDOREXPERIMENT`?

**Comment by jvshahid** [comment]
@chendrix yes but only for go1.6+. For go1.5 you are still required to set the `GO15VENDOREXPERIMENT` env variable.
