### ISSUE TITLE
Deprecated version of go (go1.5.3)

### ISSUE THREAD

**Issue by apoydence** [cloudfoundry/go-buildpack#28]
When using `"go1.5"` in my Godeps.json file, I see the following error while pushing my app:

```
!
 !     Deprecated version of go (go1.5.3)
 !     See https://devcenter.heroku.com/articles/go-support#go-versions for supported version information.
 !
```

However, the app still successfully deployed.

**Comment by davidjahn** [comment]
Hi @apoydence thanks for pointing out the issue.
We are aware, and currently have removed the warning message in our develop branch, which should be merged in a few days to master:
https://github.com/cloudfoundry/go-buildpack/commit/c519018f3406d765139196b3f918e616ac7f1609

**Comment by Dannyzen** [comment]
This has been merged into master and can be found here: https://github.com/cloudfoundry/go-buildpack/blob/master/bin/compile#L45-L47
