### ISSUE TITLE
error obtaining VCS status: exit status 128

### ISSUE THREAD

**Issue by nvasilev98** [cloudfoundry/go-buildpack#315]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.53.0+8e2b70a4a.2020-10-01

What version of the buildpack you are using?
1.9.49

What did you expect to happen?
Update from go1.17 to go1.19

What was the actual behavior?
Since we have migrated to golang version of our project to 1.19 and some of our vendored dependencies are using “any” instead of “interface” (any is an alias for interface and it is introduced in Go 1.18). In this case, when we use go_buildpack with go version 1.17 our build fails due to the undefined “any” since “any” has been introduced in Golang 1.18. However updating the GOVERSION in the deployment file - mta.yaml to go 1.19 fixes the issue above, but another one occurs:
```
   2022-11-08T15:41:16.86+0200 [STG/0] OUT -----> Running: go install -tags cloudfoundry -buildmode pie 
   github.wdf.sap.corp/cs-v2/gbaas-service/cmd/admin-api
   2022-11-08T15:41:17.06+0200 [STG/0] ERR error obtaining VCS status: exit status 128
   2022-11-08T15:41:17.06+0200 [STG/0] ERR Use -buildvcs=false to disable VCS stamping.
```
A solution we tried is to add to the env: ``` GOFLAGS: "-buildvcs=false" ```, but it did not make any change. Has somebody faced this issue and is there an appropriate way to resolve it?

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message

**Comment by arjun024** [comment]
Not sure what `mta.yaml` - it sounds like a deployment config for some specific flavor of CF.
Did you try setting GOVERSION in the app manifest (See examples https://docs.cloudfoundry.org/buildpacks/go/index.html)

I haven't seen this but if you can produce an app that reproduces the issue, we can take a deeper look

**Comment by ryanmoran** [comment]
Closing as inactive. Feel free to reopen this issue.
