### ISSUE TITLE
go 1.6 causes: Deprecated version of go (go1.6)

### ISSUE THREAD

**Issue by arekkas** [cloudfoundry/go-buildpack#32]
```
 !     
 !     Deprecated version of go (go1.6)
 !     See https://devcenter.heroku.com/articles/go-support#go-versions for supported version information.
 !     
It looks like you're trying to use go 1.6.
The versions of go supported in this buildpack are:
- 1.5.3
- 1.5.2
- 1.4.3
- 1.4.2
If you need further help, start by reading: http://github.com/cloudfoundry/go-buildpack/releases.
Failed to compile droplet
Exit status 223
```

However, Go 1.6 is officially released and should be therefore supported.

**Comment by jtarchie** [comment]
@arekkas, though it has been released, we've not updated the buildpack to support it. If you look under [releases](https://github.com/cloudfoundry/go-buildpack/releases) you'll see a table of supported versions for each buildpack release.

We have a [story](https://www.pivotaltracker.com/story/show/113958297) in Pivotal Tracker to mark the new release.

**Comment by arekkas** [comment]
Thanks for the response. Don't want to pressure or anything, but not being able to migrate to go 1.6 is painful, because of go15vendorexperiment behaviour change and godep lock. Would be great if 1.6 could land soon so i can resolve vendor issues and deploy the new codebase! :)

**Comment by arekkas** [comment]
If [this](https://github.com/cloudfoundry/go-buildpack/blob/bac190db1c62d4b3bcc9ae27fac3e24ad58fb1e1/manifest.yml) is the only thing that needs changing for go 1.6 to work, I'll gladly create a PR :)

**Comment by Dannyzen** [comment]
Hey @arekkas friendly heads up, we should have 1.6 support by mid-this week (if not earlier)

**Comment by arekkas** [comment]
:heart:
