### ISSUE TITLE
Include better documentation in the README in regards to the Procfile

### ISSUE THREAD

**Issue by dprotaso** [cloudfoundry/go-buildpack#33]
It's not obvious when viewing this repo that a Procfile is required and what it's necessary contents should be.

Probably best to link to a sample app that new developers could push.

The documentation here doesn't help: http://docs.cloudfoundry.org/buildpacks/go/index.html

**Comment by jtarchie** [comment]
Thanks for the issue. I am going to make sure that we get this out soon. We are making an effort update documentation to be better.

**Comment by RochesterinNYC** [comment]
@dprotaso Thanks for the issue. We've updated the docs in the README (https://github.com/cloudfoundry/go-buildpack/tree/develop#usage) and submitted a PR (referenced above) for the Cloudfoundry docs website as well.

**Comment by dprotaso** [comment]
Thanks!

**Comment by CAFxX** [comment]
Might be a good idea to mention that the name of the command is defined by the leaf of the Godeps.json ImportPath.

**Comment by CAFxX** [comment]
https://github.com/cloudfoundry/go-buildpack/pull/35
