### ISSUE TITLE
RFC: Removing support for Go 1.4

### ISSUE THREAD

**Issue by Dannyzen** [cloudfoundry/go-buildpack#36]
Hello!

As the [official Go release policy](https://golang.org/doc/devel/release.html) has deprecated support for Go 1.4, the Buildpacks team would like to propose the removal of Go 1.4 support from the Go buildpack as well. 

If you have any questions or concerns regarding this change we would like to hear from you! Please respond no later than 4/25, when we plan to schedule work to make the change.

**Comment by geramirez** [comment]
Version [1.7](https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.7.7) has been released and removes support for Go 1.4
