### ISSUE TITLE
Documentation is incomplete

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/go-buildpack#41]
https://docs.cloudfoundry.org/buildpacks/go/index.html has the following documentation:

> Pushing Apps with native Go vendoring
> If you are using the native Go vendoring system, which packages all local dependencies in the vendor/ directory, you must specify your app’s package name in the GOPACKAGENAME environment variable. An example manifest.yml:

> If you are using the vendor/ directory for dependencies, you can set the Go version with the GOVERSION environment variable.

Note `An example manifest.yml:` indicates an example will be specified, but then none is provided. Could this please be remedied?

Thanks!
Jean

**Comment by Dannyzen** [comment]
Thanks for the catch @jadekler. We've added this in via https://github.com/cloudfoundry/docs-buildpacks/pull/70
