### ISSUE TITLE
Inclusion of Glide in the Go buildpack

### ISSUE THREAD

**Issue by Dannyzen** [cloudfoundry/go-buildpack#42]
Prompted by Heroku's inclusion of the Glide [[1](https://github.com/Masterminds/glide)] package manager for Golang we've taken an interest in supporting Glide officially in the Go buildpack. In order to understand priority and "sought afterness" of this functionality we'd like to understand if the community would value its addition.

If you find the inclusion of Glide in the Go buildpack compelling, please +1 or comment on this issue.

[1] - https://github.com/Masterminds/glide

**Comment by krujos** [comment]
+1

**Comment by tcnksm** [comment]
+1

Now glide is getting popular. Our user will also want to use this soon.

**Comment by x6j8x** [comment]
+1

**Comment by Dannyzen** [comment]
This has been completed in 1.7.9 [[1]](https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.7.9)  If you're interested in looking at sample apps using glide you can find them here [[2]](https://github.com/cloudfoundry/go-buildpack/tree/master/cf_spec/fixtures/go_app_with_glide
) [[3]](https://github.com/cloudfoundry/go-buildpack/tree/master/cf_spec/fixtures). Finally, documentation is also available at docs.cloudfoundry.org [[4]](http://docs.cloudfoundry.org/buildpacks/go/#with_glide)

[1] - https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.7.9
[2] - https://github.com/cloudfoundry/go-buildpack/tree/master/cf_spec/fixtures/go_app_with_glide
[3] - https://github.com/cloudfoundry/go-buildpack/tree/master/cf_spec/fixtures/go_app_with_glide_and_vendoring/src/go_app_with_glide_and_vendoring
[4] - http://docs.cloudfoundry.org/buildpacks/go/#with_glide
