### ISSUE TITLE
Support for Go v1.22

### ISSUE THREAD

**Issue by remast** [cloudfoundry/go-buildpack#428]
Hi,

I updated my project to the latest Go version v1.22 and now I get this error:

```
Paketo Buildpack for Go Distribution 2.4.5
  Resolving Go version
    Candidate version sources (in priority order):
      go.mod    -> ">= 1.22"
      <unknown> -> ""
failed to satisfy "go" dependency version constraint ">= 1.22": no compatible versions on "io.buildpacks.stacks.jammy.tiny" stack. Supported versions are: [1.20.13, 1.20.14, 1.21.6, 1.21.7]
```

Is there already support for Go 1.22 or is that still missing?

Thanks,
Jan!

**Comment by brayanhenao** [comment]
Hi @remast, you are using the [Paketo](https://github.com/paketo-buildpacks/go-dist) buildpack, not the Cloudfoundry buildpack.

The latest release of CF buildpack supports go 1.22. For Paketo is a work in progress.

**Comment by remast** [comment]
Sorry and thx for the quick reply.👍
