### ISSUE TITLE
NOTICE: Default version of Go will change to 1.7.x after 2016-11-18

### ISSUE THREAD

**Issue by sclevine** [cloudfoundry/go-buildpack#46]
The version of Go in the Go Buildpack will change from version 1.6.3 to the latest 1.7.x version (currently 1.7.2) in the first release of the Go Buildpack after November 18, 2016. If you would like to continue using Go 1.6.3, please set the `$GOVERSION` environment variable in your app, or use your choice of Go dependency management utility to lock your version of Go to 1.6.3. For more information, refer to the documentation: http://docs.cloudfoundry.org/buildpacks/go/

**Comment by RochesterinNYC** [comment]
In https://github.com/cloudfoundry/go-buildpack/commit/d8c5ce611c2b54ce341b27705aff874aa224186e, the default go version was changed to `1.7.3` and then changed immediately to `1.7.4` when that go version was added to the buildpack via https://github.com/cloudfoundry/go-buildpack/commit/c93916dd79bf3d991f4fa1a775e7dbadceadd6fc
