### ISSUE TITLE
Support dep

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/go-buildpack#49]
I'm currently using [Glide](https://github.com/Masterminds/glide) to vendor my Go apps which works really well. In the near future, I'd like to switch to [Dep](https://github.com/golang/dep). It would be awesome, if the Go buildpack supported Dep.

**Comment by sclevine** [comment]
Hi @mastertinner,

Thanks for the feature request! We are also excited about dep!

However, dep is a prototype tool in the alpha development stage. It will likely change in non-backwards-compatible ways. If we include support for it in the buildpack right now, we would likely be forced to break existing applications that use dep when new versions of dep are released.

So we can't include it yet, but we will as soon as it meets our standards for stability.
