### ISSUE TITLE
We are not using the GB Package manager but getting GBError()

### ISSUE THREAD

**Issue by rkentmc** [cloudfoundry/go-buildpack#51]
We are using build pack 1.7

cf version 6.27.0+d26b32dcc.2017-06-08

I pushed my app to PCF and go back a GBError() but we are not using GB Package Manager.

It downloaded the buildpacks, staged, and then
 ``` 
[Buildpack]                      ERROR Detect failed with exception #<RuntimeError: Open JDK Like Memory Calculator error: undefined method `get' for nil:NilClass
Did you mean?  gets
               gem>
Open JDK Like Memory Calculator error: undefined method 'get' for nil:NilClass
Did you mean?  gets
               gem
-------> Buildpack version 1.7.18
file:///tmp/buildpacks/811f6eb18af9f6cd2a54e973c1358f3a/dependencies/https___buildpacks.cloudfoundry.org_dependencies_godep_godep-v78-linux-x64.tgz
file:///tmp/buildpacks/811f6eb18af9f6cd2a54e973c1358f3a/dependencies/https___buildpacks.cloudfoundry.org_dependencies_glide_glide-v0.12.3-linux-x64.tgz
-----> Using go1.7.5
 !!    
 !!    Error: Cloud Foundry does not support the GB package manager
 !!    We currently only support the Godep and Glide package managers for go apps
 !!    For support please file an issue: https://github.com/cloudfoundry/go-buildpack/issues
 !!    
Failed to compile droplet
Exit status 223
Destroying container
Successfully destroyed container

FAILED
Error restarting application: BuildpackCompileFailed

```

**Comment by sclevine** [comment]
Hi @rkentmc,

Can you upgrade to the latest version of the buildpack and see if it fixes your error?

Also, if you're a PCF customer, you can reach out to Pivotal Support at support@pivotal.io.

**Comment by rkentmc** [comment]
cf update-buildpack go_buildpack????

**Comment by sclevine** [comment]
```
cf update-buildpack go_buildpack -p /path/to/new/buildpack
```

Or just push your app with:
```
cf push yourapp -b https://github.com/cloudfoundry/go-buildpack
```

**Comment by coxcs1** [comment]
+1 
Having same issue.. and we are not using a package manager.... and are using the latest go buildpack

**Comment by rkentmc** [comment]
I used updated buildpack I am now getting this error:

```Running go build finalize
       **ERROR** To use go native vendoring set the $GOPACKAGENAME
       environment variable to your app's package name
       **ERROR** Unable to determine import path: GOPACKAGENAME unset
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container```

**Comment by sclevine** [comment]
If you aren't using any vendoring tools, have you set `GOPACKAGENAME` as documented [here](http://docs.cloudfoundry.org/buildpacks/go/index.html)?

**Comment by coxcs1** [comment]
yes sir.. still same error

**Comment by coxcs1** [comment]
we are trying to push a simple web app.. this error is rather odd..

**Comment by coxcs1** [comment]
https://github.com/christopherneuhardt/12FactorGoLibrary 

is the app we are trying to deploy... very simple.. not sure what is going on with cloud foundry   :unamused:

**Comment by sclevine** [comment]
That does not appear to be a valid Go app configured to work with CF. Please review the documentation and check out these sample apps:
https://github.com/cloudfoundry/go-buildpack/tree/master/cf_spec/fixtures

**Comment by coxcs1** [comment]
What is wrong with how it is configured? I am new to Golang and am trying to learn Cloud Foundry configs ans well. Please help lol :grinning:

**Comment by coxcs1** [comment]
It builds on my ubuntu 14.04 instance.. please help

**Comment by thequillman** [comment]
@sclevine Thank you for your help so far. The app in question has a dependency of another github: [go-sql-driver/mysql](https://github.com/go-sql-driver/mysql). Would this also throw the error?

**Comment by rkentmc** [comment]
@sclevine Yes, I set the GOPACKAGENAME and got the same error. I am using the standard pkg/bin/src config that the Go docs suggest for a project.
_

**Comment by sclevine** [comment]
I think you are pushing from the directory that contains `src`, instead of the package directory.
See the examples here: https://github.com/cloudfoundry/go-buildpack/tree/master/cf_spec/fixtures
Those examples are pushed from the directory that contains the `manifest.yml` file.

**Comment by thequillman** [comment]
@sclevine After restructuring the tree, we were unsuccessful in building with a vendor in Linux 14.04 and cloudfoundry. It instead throws an error saying it can't find github.com/mysql even though it's there. And if I were to change the import going up two levels, it throws an error  I'm assuming it's looking in the wrong bin. 

This is the error I'm getting. 
`index.go:11:2: cannot find package "github.com/mysql" in any of: 
    /usr/local/go/src/github.com/mysql (from $GOROOT)
    /home/jon/go/src/github.com/mysql (from $GOPATH)`

**Comment by sclevine** [comment]
When I push your app, the error I get is:
```
./index.go:11: imported and not used: "12FactorGoLibrary/vendor/github.com/mysql"
       **ERROR** Unable to compile application: exit status 2
```
This is because you aren't actually using the library in your code. If I make Go ignore this, by changing the import:
```
_ "github.com/mysql"
```
Your app pushes successfully (with v1.8.5):
```
requested state: started
instances: 1/1
usage: 128M x 1 instances
urls: library-go-web-app-hexastichic-inseparableness.cfapps.io
last uploaded: Fri Jul 21 16:39:08 UTC 2017
stack: cflinuxfs2
buildpack: go_buildpack

     state     since                    cpu    memory      disk      details
#0   running   2017-07-21 12:39:46 PM   0.0%   0 of 128M   0 of 1G
```

The need to import the `github.com/go-sql-driver/mysql` package with `_` is documented in the [README for that driver](https://github.com/go-sql-driver/mysql/blob/master/README.md).

I might also recommend that you use the actual repo name in your `vendor` directory, instead of a made-up repo name ("github.com/mysql").

**Comment by thequillman** [comment]
We had done something like this earlier. 

But I'm not sure that answers my issue. May I ask what your tree using this app looks like?

**Comment by sclevine** [comment]
```
liberty:src pivotal$ git st
On branch test
Your branch is up-to-date with 'origin/test'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   index.go

no changes added to commit (use "git add" and/or "git commit -a")
liberty:src pivotal$ git diff
diff --git a/src/index.go b/src/index.go
index a6ec2f2..e274907 100644
--- a/src/index.go
+++ b/src/index.go
@@ -8,7 +8,8 @@ import (
        "html/template"
        "net/http"
        "regexp"
-       "github.com/mysql"
+
+       _ "github.com/mysql"
 )

 var validPath = regexp.MustCompile("^/(index.html|admin.html|test.html)$")
liberty:src pivotal$ pwd
/Users/pivotal/workspace/buildpacks/issues/12FactorGoLibrary/src
liberty:src pivotal$ cf push
Using manifest file /Users/pivotal/workspace/buildpacks/issues/12FactorGoLibrary/src/manifest.yml

Creating app library-go-web-app in org slevine-org / space development as slevine@pivotal.io...
OK

Creating route library-go-web-app-corniculate-firecracker.cfapps.io...
OK

Binding library-go-web-app-corniculate-firecracker.cfapps.io to library-go-web-app...
OK

Uploading library-go-web-app...
Uploading app files from: /Users/pivotal/workspace/buildpacks/issues/12FactorGoLibrary/src
Uploading 206.6K, 72 files
Done uploading
OK

Starting app library-go-web-app in org slevine-org / space development as slevine@pivotal.io...
Downloading go_buildpack...
Downloaded go_buildpack
Creating container
Successfully created container
Downloading app package...
Downloaded app package (3.3M)
-----> Installing godep v79
       Copy [/tmp/buildpacks/54970fe06aa72b324386db7fb789b17f/dependencies/https___buildpacks.cloudfoundry.org_dependencies_godep_godep-v79-linux-x64-9e37ce0f.tgz]
-----> Go Buildpack version 1.8.5
-----> Installing glide v0.12.3
       Copy [/tmp/buildpacks/54970fe06aa72b324386db7fb789b17f/dependencies/https___buildpacks.cloudfoundry.org_dependencies_glide_glide-v0.12.3-linux-x64-aa256363.tgz]
-----> Installing go 1.8.3
       Copy [/tmp/buildpacks/54970fe06aa72b324386db7fb789b17f/dependencies/https___buildpacks.cloudfoundry.org_dependencies_go_go1.8.3.linux-amd64-32ec5ac6.tar.gz]
       **WARNING** Installing package '.' (default)
-----> Running: go install -tags cloudfoundry -buildmode pie .
Exit status 0
Uploading droplet, build artifacts cache...
Uploading build artifacts cache...
Uploading droplet...
Uploaded build artifacts cache (212B)
Uploaded droplet (6.4M)
Uploading complete
Destroying container
Successfully destroyed container

1 of 1 instances running

App started


OK

App library-go-web-app was started using this command `12FactorGoLibrary`

Showing health and status for app library-go-web-app in org slevine-org / space development as slevine@pivotal.io...
OK

requested state: started
instances: 1/1
usage: 128M x 1 instances
urls: library-go-web-app-corniculate-firecracker.cfapps.io
last uploaded: Fri Jul 21 19:02:12 UTC 2017
stack: cflinuxfs2
buildpack: go_buildpack

     state     since                    cpu    memory      disk      details
#0   running   2017-07-21 03:02:45 PM   0.0%   0 of 128M   0 of 1G
```

**Comment by thequillman** [comment]
@sclevine Okay, I think I see where we disconnected. It's my understanding that you're using the command line version while we're using a Concourse to build this project. 
Also, I forgot to thank you for your find earlier about the `_"github.com/mysql"` debacle. So thank you for that!
As for my issue in building in Linux 14.04, that was simple error on my part. 
Again, thank you very much for your help.

**Comment by sclevine** [comment]
👍
