### ISSUE TITLE
Failed to execute buildpack test with cf cli version 6.26.Looks like machete issue, so proposing higher version of machete.

### ISSUE THREAD

**Issue by kanekoh** [cloudfoundry/go-buildpack#52]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

cf version 6.26.0+9c9a261.2017-04-06

What version of the buildpack you are using?

1.8.5 (which uses machete version 0.0.66)

If you were attempting to accomplish a task, what was it you were attempting to do?

Executed go-buildpack tests with the following command.
`BUNDLE_GEMFILE=cf.Gemfile bundle exec buildpack-build`

What did you expect to happen?

All tests pass.

What was the actual behavior?

Got following error during tests. the cause is cf cli changed the tag 'urls:' to 'routes:' half a year back .

```
1) CF Binary Buildpack deploying a Ruby script when specifying a buildpack deploys successfully
   Failure/Error: browser.visit_path('/')
   
   RuntimeError:
     Failed finding app URL
     response:
   
     Showing health and status for app webrick_app in org pivotal / space integration as admin...
   
     name:              webrick_app
     requested state:   started
     instances:         1/1
     usage:             1G x 1 instances
     routes:            webrick-app.bosh-lite.com
     last uploaded:     Thu 27 Jul 08:11:00 UTC 2017
     stack:             cflinuxfs2
     buildpack:         binary-test-buildpack
      
             state     since                  cpu    memory    disk      details
      #0   running   2017-07-27T08:11:14Z   0.0%   0 of 1G   0 of 1G   
      # ./cf_spec/integration/deploy_a_binary_app_spec.rb:19:in `block (4 levels) in <top (required)>'
```
Then I tried using mechete v 0.0.67 but faced another problem as  following.

```
9) CF Go Buildpack with cached buildpack dependencies go 1.7 app with GO_INSTALL_TOOLS_IN_IMAGE running a task can find the specifed go in the container
   Failure/Error: before { skip_if_no_run_task_support_on_targeted_cf }
   
     Output was: api endpoint:   https://api.fastcloud.com
     api version:    2.77.0
    # ./cf_spec/spec_helper.rb:19:in `skip_if_no_run_task_support_on_targeted_cf'
    # ./cf_spec/integration/deploy_a_go_app_spec.rb:267:in `block (5 levels) in <top (required)>'
     can find the specifed go in the container (FAILED - 9)
```

Then I tried using mechete v 0.0.68 which looks good for most latest cf cli. Didn't try any further with higher versions of machete though.

Please confirm where necessary:
* [*] I have included a log output
* [*] My log includes an error message
* [*] I have included steps for reproduction

**Comment by dgodd** [comment]
Hi @kanekoh Yes unfortunately the latest version of machete on master does not work with the latest cf cli (the output changed). We bumped machete for exactly that reason and you can see it is being used on the develop branch of the go buildpack (machete v0.0.70). We will release develop to master shortly.

Did bumping to 0.0.68 work for you? If so I will close this and prioritize pushing develop to master sooner.

**Comment by kanekoh** [comment]
Hi @dgodd, 
Thanks for you reply. Yes, bumped machete to 0.0.68 works for me.
