### ISSUE TITLE
go-buildpack incorrectly reports 'GB package manger' error just because of `src/` directory existing

### ISSUE THREAD

**Issue by dnwe** [cloudfoundry/go-buildpack#57]
### What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

v2.92.0 && v6.32

### What version of the buildpack you are using?

Latest (1.8.17 at time of writing)

### If you were attempting to accomplish a task, what was it you were attempting to do?

Deploy a Go-based application using a glide.yaml, but a `src/` directory at the top-level

### What did you expect to happen?

Successful deployment.

### What was the actual behavior?

Similar to https://github.com/cloudfoundry/go-buildpack/issues/51

```
!!    
!!    Error: Cloud Foundry does not support the GB package manager
!!    We currently only support the Godep and Glide package managers for go apps
!!    For support please file an issue: https://github.com/cloudfoundry/go-buildpack/issues
!!    
```

A quick glance at the SelectVendorTool() func in [supply/supply.go#L78-L143](https://github.com/cloudfoundry/go-buildpack/blob/8cd66701cb3cf6712119e97fe638aa16066464c4/src/go/supply/supply.go#L78-L143) code shows an unusual ordering of the logic whereby it will error out as soon as it encounters a `src/` directory (which it assumes to mean someone is attempting to use the old GB package manager) despite the existence of a glide.yaml, because it doesn't check that until later.

The fix for this behaviour would be to move the code around in SelectVendorTool such that glide.yaml/Godeps.json/Gopkg.toml are checked for up-front and used if available, and any other error reporting is performed afterwards.

### Please confirm where necessary:
* [ x ] I have included a log output
* [ x ] My log includes an error message
* [ x ] I have included steps for reproduction

**Comment by sclevine** [comment]
@dgodd We should not fail staging immediately if `src` is detected. I'm prioritizing this as a bug.

**Comment by webbbret** [comment]
It's been a while with no progress or resolution I believe. If I have a /src folder and do a push, I get the following:

`   -----> Go Buildpack version 1.8.30
          **ERROR** Cloud Foundry does not support the GB package manager.
          We currently only support the Godep, Glide and dep package managers for go apps.
          For support please file an issue: https://github.com/cloudfoundry/go-buildpack/issues
          **ERROR** Unable to select Go vendor tool: gb unsupported
`

If I rename the SRC folder to something else, I get the following:

`   -----> Running: go install -tags cloudfoundry -buildmode pie .
   can't load package: package kafka-firehose-nozzle: no Go files in /tmp/gobuildpack.gopath121497756/.go/src/kafka-firehose-nozzle
          **ERROR** Unable to compile application: exit status 1
   Failed to compile droplet: Failed to run finalize script: exit status 12
`
Complains about no Go files in a tmp go folder... What is going on. How do I push the kafka-firehose-nozzle that you guys promote on your web pages using cf if I cannot have a src folder present... is this scheduled for fixing or not? Many thanks in advance.

**Comment by chhhavi** [comment]
@dnwe Sorry for the delay in action. We were wondering if you are still having this issue? And if you are, could you give us a sample app?

**Comment by kardolus** [comment]
@dnwe We were able to reproduce this issue using one of [our fixtures](https://github.com/cloudfoundry/go-buildpack/tree/master/fixtures/with_glide). When you push the app from the with glide root directory using `cf p -b go_buildpack` you get the error you describe. The tricky part here is that GB apps are detected based on the existence of a src dir. We were able to resolve your issue by pushing with the following command instead `cf p -b go_buildpack -p src/with_glide/`.

Let us know if this works for you, in the meantime we will work on a more descriptive error message.

**Comment by dnwe** [comment]
@kardolus I'd raised on behalf of a customer, but I can try it out. However, I'm not sure why you'd improve the error message rather than just re-ordering the detection so that you check for the more likely package managers first like I suggested in the original post
