### ISSUE TITLE
CF unable to find local packages when using dep

### ISSUE THREAD

**Issue by coding-yogi** [cloudfoundry/go-buildpack#58]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.27.0+d26b32dcc.2017-06-08

What version of the buildpack you are using?
Go Buildpack version 1.8.18

If you were attempting to accomplish a task, what was it you were attempting to do?
Deploying app to CF 

What did you expect to happen?
App should be deployed successfully and start

What was the actual behavior?
Deployment fails as local packages were not found. Issue is "dep" doesn't package local packages and so local packages are not found in /vendor dir

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [ ] I have included steps for reproduction

**logs:** 
main.go:10:2: cannot find package **"github.com/coding-yogi/grpcserver/employee"** in any of:
        /tmp/gobuildpack.gopath689887214/.go/src/go18_dep/vendor/github.com/coding-yogi/grpcserver/employee (vendor tree)
        /tmp/contents889922188/deps/0/go1.8.7/go/src/github.com/coding-yogi/grpcserver/employee (from $GOROOT)
        /tmp/gobuildpack.gopath689887214/.go/src/github.com/coding-yogi/grpcserver/employee (from $GOPATH)
       **ERROR** Unable to compile application: exit status 1
Failed to compile droplet: Failed to run finalize script: exit status 12
Exit status 223
Stopping instance 55e96c47-3ee4-4ade-bfe1-17ca966f3542
Destroying container
Successfully destroyed container

**"github.com/coding-yogi/grpcserver/employee"** is my local package

**Comment by sclevine** [comment]
Can you try with `GOPACKAGENAME` set to `github.com/coding-yogi/grpcserver`?
I don't think it's possible for the buildpack to determine the fully-qualified name of your package without that env var. Dep does not store that information.

**Comment by coding-yogi** [comment]
Oh, that works! nice! I had set this env var to ```GOPACKAGENAME: go18_dep``` looking at the sample app

**Comment by coding-yogi** [comment]
any idea if CF supports gRPC based server app? cos it seems my app is compiled by CF is unable to start the app
