### ISSUE TITLE
More aggressive default of go version

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/go-buildpack#64]
Currently we are defaulting to an old go version 1.8.x https://github.com/cloudfoundry/go-buildpack/blob/master/manifest.yml#L3-L5

The go core team have promised that 1.X is always upgradable; so could we always bump the default version to the latest 1.X version?

**Comment by sclevine** [comment]
@drnic thanks for pointing this out. We should also drop 1.6.x and 1.7.x. We will need a 30-day notice for this change (policy, and  because we've occasionally observed changes in behavior in minor Go version bumps).

@ssisil for when you return.

**Comment by sclevine** [comment]
This change is on develop and will go out in the next release. Apologies for the delay.
