### ISSUE TITLE
Allow to build/run app with race detector enabled

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/go-buildpack#66]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

2.98.0, 6.37.0

What version of the buildpack you are using?

master

If you were attempting to accomplish a task, what was it you were attempting to do?

Run my go application with the race detector on

What did you expect to happen?

The application runs with the race detector enabled

What was the actual behavior?

No documented way to run an app with the race detector enabled

**Comment by shanks3012** [comment]
We recommend that you check for race conditions during testing and not when deploying. Closing this is issue for now.
