### ISSUE TITLE
bower 1.8.0 is a dependency of go-buildpack 1.8.20????

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/go-buildpack#67]
Hi, 
my team would like to use go-buildpack 1.8.20 and to approve that I've to analyze it's source code and the code of its dependencies chain, to be sure that they don't have problematic licenses.

Now the analysis evidenced _### bower 1.8.0_ as a dependency (along with all its dependencies chain) but I do not see any reference of bower 1.8.0 in the https://buildpacks.cloudfoundry.org/#/dependencies, where I see bower listed as secondary dependency only for Dotnet Core Buildpack v1.0.26 instead.

Is it bower 1.8.0 a dependency of go-buildpack 1.8.20 or not ?

Could you please clarify?

Many thanks.

**Comment by sclevine** [comment]
Can you explain why you believe that bower is a dependency of this buildpack?

**Comment by luisapace** [comment]
Hi, sure! 
it comes from:
https://github.com/cloudfoundry/go-buildpack/blob/v1.8.20/src/go/vendor/github.com/cloudfoundry/libbuildpack/fixtures/manifest/standard/manifest.yml

along with bower 1.9.0 and others.

**Comment by sclevine** [comment]
Note `fixtures` in the path, and see https://github.com/cloudfoundry/binary-buildpack/issues/21.

**Comment by astrieanna** [comment]
This question has been answered. (Anything in `fixtures` is only for tests, not in the final buildpack.)
