### ISSUE TITLE
Doesn't work with any stacks apart of cflinuxfs2 and cflinuxfs3

### ISSUE THREAD

**Issue by b10s** [cloudfoundry/go-buildpack#73]
Seems the [commit](https://github.com/cloudfoundry/go-buildpack/commit/e89eb69d3c4010f1f3d7a2aa4420029e1454ee65) brings restriction to use only cflinuxfs2 or cflinuxfs3 stacks.

Otherwise staging will end with the following error message:
```
...
/tmp/buildpackdownloads/00baaa6ae45f2bb9298fa2e8f5685eb8/scripts/install_go.sh: line 17: GO_SHA256: unbound variable
...
```

**Comment by giner** [comment]
I think I hasn't been supposed to be used with any other stacks rather than cflinuxfs2 (initially) and cflinuxfs3 (from recently).

**Comment by tylerphelan** [comment]
@b10s This commit would only affect the online buildpack case (`cf push app -b https://github.com/cloudfoundry/go-buildpack`) as it uses Go to build the buildpack from source. The buildpack also only supports cflinuxfs2 and cflinuxfs3 on `master`, are you using a forked version of the buildpack?

**Comment by b10s** [comment]
@tylerphelan we use online buildpack as you mentioned: `https://github.com/cloudfoundry/go-buildpack` on CF deployment which has stack `foo` as an alias for `cflinuxfs2`

**Comment by ndon55555** [comment]
@b10s Where exactly are you seeing `foo`?

**Comment by tylerphelan** [comment]
@b10s what's the use case for aliasing the rootfs?

A workaround for this could be forking the buildpack and updating [this line](https://github.com/cloudfoundry/go-buildpack/blob/e89eb69d3c4010f1f3d7a2aa4420029e1454ee65/scripts/install_go.sh#L17) to use a different version of Go.

**Comment by b10s** [comment]
@tylerphelan we have old workaround to separate environments: dev, stg and pro using stacks.

Seems I'm wrong with the proposal to allow any stacks (because go-buildpack created and tested only for cflinuxfs2 and cflinuxfs3).

Would be great to have an error message: `go-buildpack supports only cflinuxfs2 and cflinuxfs3 stacks` instead of `GO_SHA256: unbound variable`.

Since the stack is [not a constant value](https://docs.cloudfoundry.org/running/custom-stack.html), some deployment may have different stacks, a mention in documentation why and what stack(s) supported will make usage of go-buildpack clearer.

**Comment by kardolus** [comment]
Hi @b10s! We fixed this on the [develop branch](https://github.com/cloudfoundry/go-buildpack/tree/develop). Would be great if you could perhaps give it a spin. No pressure.

**Comment by b10s** [comment]
Thanks!
Seems more clear : )

```
          **ERROR** Unsupported stack
                    See https://docs.cloudfoundry.org/devguide/deploy-apps/stacks.html for more info
   Failed to compile droplet: Failed to run all supply scripts: exit status 1
```
