### ISSUE TITLE
Unable to build go-buildpack from source code

### ISSUE THREAD

**Issue by ngscchung** [cloudfoundry/go-buildpack#76]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
PCF 2.4.2

What version of the buildpack you are using?
Go Buildpack 1.8.36

If you were attempting to accomplish a task, what was it you were attempting to do?
Build cached go-buildpack from source code

What did you expect to happen?
To build go-buildpack zip file with cached binaries included

What was the actual behavior?
Run the below command according to readme.md:
(cd src/go/vendor/github.com/cloudfoundry/libbuildpack/packager/buildpack-packager && go install)

-bash: cd: src/go/vendor/github.com/cloudfoundry/libbuildpack/packager/buildpack-packager: No such file or directory

Then tried the followings:
1) I think .envrc was wrong, so updated GOBIN=$(pwd)/bin 
2) go get github.com/google/subcommands
3) go get github.com/cloudfoundry/libbuildpack
4) (cd ~/go/src/github.com/cloudfoundry/libbuildpack/packager/buildpack-packager && go install)
5) buildpack-packager build --cached=true -any-stack

Full error log prompted as below:
++ dirname scripts/build.sh
+ cd scripts/..
+ source .envrc
+++ pwd
++ export GOBIN=/tmp/buildpack-packager755485061/bin
++ GOBIN=/tmp/buildpack-packager755485061/bin
++ export PATH= [...]
++ PATH=[...]
+ GOOS=linux
+ go build -mod=vendor '-ldflags=-s -w' -o bin/supply ./src/go/supply/cli
flag provided but not defined: -mod
usage: build [-o output] [-i] [build flags] [packages]

Build compiles the packages named by the import paths,
along with their dependencies, but it does not install the results.

If the arguments to build are a list of .go files, build treats
them as a list of source files specifying a single package.

When compiling a single main package, build writes
the resulting executable to an output file named after
the first source file ('go build ed.go rx.go' writes 'ed' or 'ed.exe')
or the source code directory ('go build unix/sam' writes 'sam' or 'sam.exe').
The '.exe' suffix is added when writing a Windows executable.

When compiling multiple packages or a single non-main package,
build compiles the packages but discards the resulting object,
serving only as a check that the packages can be built.

When compiling packages, build ignores files that end in '_test.go'.

The -o flag, only allowed when compiling a single package,
forces build to write the resulting executable or object
to the named output file, instead of the default behavior described
in the last two paragraphs.

The -i flag installs the packages that are dependencies of the target.

The build flags are shared by the build, clean, get, install, list, run,
and test commands:

        -a
                force rebuilding of packages that are already up-to-date.
        -n
                print the commands but do not run them.
        -p n
                the number of programs, such as build commands or
                test binaries, that can be run in parallel.
                The default is the number of CPUs available.
        -race
                enable data race detection.
                Supported only on linux/amd64, freebsd/amd64, darwin/amd64 and windows/amd64.
        -msan
                enable interoperation with memory sanitizer.
                Supported only on linux/amd64,
                and only with Clang/LLVM as the host C compiler.
        -v
                print the names of packages as they are compiled.
        -work
                print the name of the temporary work directory and
                do not delete it when exiting.
        -x
                print the commands.

        -asmflags 'flag list'
                arguments to pass on each go tool asm invocation.
        -buildmode mode
                build mode to use. See 'go help buildmode' for more.
        -compiler name
                name of compiler to use, as in runtime.Compiler (gccgo or gc).
        -gccgoflags 'arg list'
                arguments to pass on each gccgo compiler/linker invocation.
        -gcflags 'arg list'
                arguments to pass on each go tool compile invocation.
        -installsuffix suffix
                a suffix to use in the name of the package installation directory,
                in order to keep output separate from default builds.
                If using the -race flag, the install suffix is automatically set to race
                or, if set explicitly, has _race appended to it.  Likewise for the -msan
                flag.  Using a -buildmode option that requires non-default compile flags
                has a similar effect.
        -ldflags 'flag list'
                arguments to pass on each go tool link invocation.
        -linkshared
                link against shared libraries previously created with
                -buildmode=shared.
        -pkgdir dir
                install and load all packages from dir instead of the usual locations.
                For example, when building with a non-standard configuration,
                use -pkgdir to keep generated packages in a separate location.
        -tags 'tag list'
                a list of build tags to consider satisfied during the build.
                For more information about build tags, see the description of
                build constraints in the documentation for the go/build package.
        -toolexec 'cmd args'
                a program to use to invoke toolchain programs like vet and asm.
                For example, instead of running asm, the go command will run
                'cmd args /path/to/asm <arguments for asm>'.

The list flags accept a space-separated list of strings. To embed spaces
in an element in the list, surround it with either single or double quotes.

For more about specifying packages, see 'go help packages'.
For more about where packages and binaries are installed,
run 'go help gopath'.
For more about calling between Go and C/C++, run 'go help c'.

Note: Build adheres to certain conventions such as those described
by 'go help gopath'. Not all projects can follow these conventions,
however. Installations that have their own conventions or that use
a separate software build system may choose to use lower-level
invocations such as 'go tool compile' and 'go tool link' to avoid
some of the overheads and design decisions of the build tool.

See also: go install, go get, go clean.

2019/03/26 07:21:02 error while creating zipfile: exit status 2

Please confirm where necessary:
* [X ] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction

**Comment by tylerphelan** [comment]
@ngscchung The README was out of date. Try this with go >=1.11:
```
go install github.com/cloudfoundry/libbuildpack/packager/buildpack-packager
buildpack-packager build --cached --stack cflinuxfs3
```
