### ISSUE TITLE
Pushing a first go application is not self explanatory

### ISSUE THREAD

**Issue by shawn-ogg** [cloudfoundry/go-buildpack#79]
Hello,

pushing your first go application is not fully documented. I ran into a few issues which I could not figure out using the documentation.

In the section **Push an App with Native Go Vendoring**:
- Where should I put the `manifest.yml`? (it is referenced to the _root directory_ with no further explanation)
- What is the meaning of the content of the manifest.yml?
- Which parts are optional ? (I ended up only defining name)
- The `GOPACKAGENAME` part was very misleading. (I had to figure out with the cf logs, how to map the relative path. Turns out I didn't need it at all)

That may all be silly questions, but as somebody who is new to CF and want's to try out his first `cf push` they matter.

**Comment by kardolus** [comment]
Hi @shawn-ogg, thanks for the feedback! You make a good point. The `GOPACKAGENAME` environment variable is not required anymore when you are using native go vendoring. We should update our documentation. We will prioritize this.

**Comment by kardolus** [comment]
@shawn-ogg we updated our documentation and submitted a PR to the docs team. Once merged the changes will be reflected on https://docs.cloudfoundry.org/buildpacks/go/index.html within a week or so.

PR is here: https://github.com/cloudfoundry/docs-buildpacks/pull/244

Thanks again for your feedback!
