### ISSUE TITLE
Add support to extend build flags similar to load flags in the buildpack

### ISSUE THREAD

**Issue by pavankrish123** [cloudfoundry/go-buildpack#81]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

`version 6.40.0+07673feb9.2018-10-08`

`$ cf curl /v2/info
{
   "name": "Pivotal Application Service",
   "build": "2.2.3-build.9",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "https://docs.pivotal.io/pivotalcf/2-2/pcf-release-notes/runtime-rn.html",
   "authorization_endpoint": "https://login.sys.pie-multi-az-blue.cfplatformeng.com",
   "token_endpoint": "https://uaa.sys.pie-multi-az-blue.cfplatformeng.com",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "api_version": "2.112.0",
   "app_ssh_endpoint": "ssh.sys.pie-multi-az-blue.cfplatformeng.com:2222",
   "app_ssh_host_key_fingerprint": "6b:db:70:ce:e7:44:12:c6:93:9e:c9:2a:b6:b0:6e:70",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.sys.pie-multi-az-blue.cfplatformeng.com:443",
   "routing_endpoint": "https://api.sys.pie-multi-az-blue.cfplatformeng.com/routing",
   "user": "70bd8ca2-b312-4a86-89c9-8b865a63c487"
}`

What version of the buildpack you are using?

`go_buildpack-cached-cflinuxfs2-v1.8.25.zip`

If you were attempting to accomplish a task, what was it you were attempting to do?

I was hoping to extend GO build flags, specifically `-tags ` in my case to achieve condition compilation 
but it looks like the build flags are hardcoded in the source of buildpack

What did you expect to happen?

The buildpack should compile the application with build flags passed via a well defined environment 
variable similar to load flags

What was the actual behavior?

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by Zanadar** [comment]
@pavankrish123 This seems like a good feature. We'll look into it.

**Comment by ryanmoran** [comment]
Its not clear that it would make sense at the moment to expose all build flags to the end user. We can certainly add support for specifying extra tags though.

**Comment by ForestEckhardt** [comment]
We're gonna close this as inactive. Please feel free to re-open if you have further issues.

**Comment by pavankrish123** [comment]
Thanks @ForestEckhardt - I am assuming the tags feature will be in buildpack?
